---
- name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

- name: Install dependencies (only if Docker is missing)
  yum:
    name: yum-utils
    state: present
  when: docker_check.failed

- name: Install Docker (only if missing)
  yum:
    name: docker
    state: present
  when: docker_check.failed

- name: Start & enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy webapp folder (Dockerfile + app.py) to EC2
  copy:
    src: webapp/
    dest: /home/ec2-user/webapp/
    mode: '0755'

- name: Build Docker image only when Dockerfile or app changes
  community.docker.docker_image:
    name: mywebapp
    build:
      path: /home/ec2-user/webapp

- name: Run web application container only when image changes
  community.docker.docker_container:
    name: webapp
    image: mywebapp:latest
    state: started
    recreate: false
    restart_policy: always
    published_ports:
      - "80:80"
