name: Terraform + Ansible Deployment

on:
  push:
    branches:
      - development
    paths:
      - 'terraform/**'
      - 'ansible/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # -----------------------------
    # AWS Authentication
    # -----------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # -----------------------------
    # Terraform Setup
    # -----------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve
    
    - name: Wait for EC2 initialization
      run: sleep 20

    # -----------------------------
    # Install AWS CLI
    # -----------------------------
    - name: Install AWS CLI
      run: |
        sudo apt update
        sudo apt install -y unzip
        aws --version
    # -----------------------------
    # Download Key 
    # -----------------------------
    - name: Download private key from S3
      run: aws s3 cp s3://kar-backend-terraform-state-bucket/keys/krishna-ec2-key.pem terraform/id_rsa.pem && chmod 600 terraform/id_rsa.pem

    # -----------------------------
    # Install Ansible
    # -----------------------------

    - name: Install Ansible dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install ansible ansible-lint

    # -----------------------------
    # Prepare Ansible Inventory check
    # -----------------------------
    - name: Show folder tree
      run: |
        sudo apt-get install -y tree
        ls -la
        pwd
        sudo tree -ap --dirsfirst /home/runner/work/nasadmin-project-repo/nasadmin-project-repo

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: ansible-playbook -i terraform/inventory.ini ansible/playbook.yml --extra-vars "app_version=${GITHUB_SHA::7}"