name: Terraform + Ansible Deployment

on:
  push:
    branches: [ "development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # -----------------------------
    # AWS Authentication
    # -----------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # -----------------------------
    # Terraform Setup
    # -----------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: terraform apply -auto-approve

    - name: Terraform Apply
      working-directory: terraform
      run: terraform output ec2_public_ip

    # -----------------------------
    # Install AWS CLI
    # -----------------------------
    - name: Install AWS CLI
      run: |
        sudo apt update
        sudo apt install -y unzip
        aws --version
    # -----------------------------
    # Download Key 
    # -----------------------------
    - name: Download private key from S3
      run: aws s3 cp s3://kar-backend-terraform-state-bucket/keys/krishna-ec2-key.pem terraform/id_rsa && chmod 600 terraform/id_rsa

    # -----------------------------
    # Install Ansible
    # -----------------------------
    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    # -----------------------------
    # Prepare Ansible Inventory check
    # -----------------------------
    - name: Debug Inventory
      run: cat terraform/inventory.ini
  
    - name: Debug Inventory
      run: cat ansible/inventory.ini

    - name: Run Ansible Playbook
      run: ansible-playbook -i terraform/inventory.ini ansible/playbook.yml
#ansible-playbook -i ansible/inventory.ini ansible/playbook.yml

    # -----------------------------
    # Run Ansible Playbook
    # -----------------------------
    #- name: Run Ansible Playbook
    #  working-directory: ansible