name: Destroy AWS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type DESTROY to confirm"
        required: true
        default: ""

jobs:
  destroy:
    if: github.event.inputs.confirm_destroy == 'DESTROY'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform
        shell: bash
        run: |
         terraform destroy -auto-approve \
           -target=aws_instance.web \
           -target=aws_internet_gateway.igw \
           -target=aws_key_pair.generated_key \
           -target=aws_route_table_association.public_assoc \
           -target=aws_route_table.public_rt \
           -target=aws_security_group.web \
           -target=aws_subnet.public \
           -target=aws_vpc.main \
           -target=aws_s3_object.ssh_private_key \
           -target=tls_private_key.ssh_key 